---
name: "rbrightling.fileserver.nfs"

on:
  push:
    paths:
      - 'roles/nfs/**'
      - 'molecule/nfs/**'
      - '.github/workflows/nfs.yml'
      - 'tox.ini'

jobs:
  call_reusable_workflow:
    uses: ./.github/workflows/reusable-ansible-test-role.yml
    with:
      role-name: 'nfs'
